export enum AttendanceErrorCode {
  InvalidDeviceId = 'INVALID_DEVICE_ID',
  AttendanceNotRequired = 'ATTENDANCE_NOT_REQUIRED',
  CheckInModeNotAllowed = 'CHECK_IN_MODE_NOT_ALLOWED',
  StudentNotOnboarded = 'STUDENT_NOT_ONBOARDED',
  OfficeNetworkRequired = 'OFFICE_NETWORK_REQUIRED',
  StudentAlreadyCheckedIn = 'STUDENT_ALREADY_CHECKED_IN',
  DeviceAlreadyUsed = 'DEVICE_ALREADY_USED',
  InvalidLeaveDate = 'INVALID_LEAVE_DATE',
  LeaveDateOutOfRange = 'LEAVE_DATE_OUT_OF_RANGE',
  LeaveAlreadyRegistered = 'LEAVE_ALREADY_REGISTERED',
  AttendanceAlreadyRecorded = 'ATTENDANCE_ALREADY_RECORDED',
  LeaveCancellationDateNotFuture = 'LEAVE_CANCELLATION_DATE_NOT_FUTURE',
  LeaveRecordNotFound = 'LEAVE_RECORD_NOT_FOUND',
  LeaveNotCancellable = 'LEAVE_NOT_CANCELLABLE',
  CalendarDateRangeInvalid = 'CALENDAR_DATE_RANGE_INVALID',
  CalendarDateRangeTooLarge = 'CALENDAR_DATE_RANGE_TOO_LARGE',
  CalendarExceptionConflict = 'CALENDAR_EXCEPTION_CONFLICT',
  CalendarExceptionNotFound = 'CALENDAR_EXCEPTION_NOT_FOUND',
  CheckInWindowClosed = 'CHECK_IN_WINDOW_CLOSED',
}
